name : CI/CD Pipeline

on:
  push :
    branches: [main]
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout code
        uses:  actions/checkout@v5

      - name: Setup Nodejs
        uses:  actions/checkout@v3
        with:
          node-version: 16
      - name: install dependencies
        run : npm install
      - name: build test
        run : npm build
